
<!DOCTYPE html>
<html lang="en" manifest="cache.manifest">

<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Uwi Web App</title>

  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  	<link href="css/index.css" rel="stylesheet">

	<style type="text/css">
	</style>

<title>Uwi Web App</title>
</head>

<body id="bg" data-spy="scroll" data-target=".navbar" data-offset="50">

<!-- **************************************************************************************************** -->
<!-- Carousel -->
	 
	  <div id="myCarousel" class="carousel slide" data-ride="carousel">
	    <!-- Indicators -->
	    <ol class="carousel-indicators">
	      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	      <li data-target="#myCarousel" data-slide-to="1"></li>
	      <li data-target="#myCarousel" data-slide-to="2"></li>
	      <li data-target="#myCarousel" data-slide-to="3"></li>
	    </ol>

	    <!-- Wrapper for slides -->
	    <div class="carousel-inner" role="listbox">

	      <div class="item active">
	        <img class="img-responsive center-block" src="img/uwi1.jpg" alt="UWI St.Augustine" width="460px" height="345px">
		      <div class="carousel-caption">
			    <h3>UWI</h3>
			    <p>Uwi Campus St.Augustine Trinidad and Tobago.</p>
			  </div>
	      </div>

	      <div class="item">
	        <img class="img-responsive center-block" src="img/uwi2.jpg" alt="UWI St.Augustine" width="460px" height="345px">
	        <div class="carousel-caption">
			    <h3>UWI</h3>
			    <p>Uwi Campus St.Augustine Trinidad and Tobago.</p>
			</div>
	      </div>
	    
	     
	    </div>

	    <!-- Left and right controls -->
	    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
	      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	      <span class="sr-only">Previous</span>
	    </a>
	    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
	      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	      <span class="sr-only">Next</span>
	    </a>
	  </div>
	
<!-- **************************************************************************************************** -->
<!-- Nav Bar top of page -->

	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container-fluid">
	    <div class="navbar-header">
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">UWI MOBILE</a>
	    </div>
	    <div>
	      <div class="collapse navbar-collapse" id="myNavbar">
	        <ul class="nav navbar-nav">
	          <li><a href="#section1">About the Uwi</a></li>
	          <li><a href="#section2">Campus Life</a></li>
	          <li><a href="#section3">How To Apply</a></li>
	          <li><a href="#section4">Our Programmes</a></li>
	          <li><a href="#section5">Contact Us</a></li>
	        </ul>
	      </div>
	    </div>
	  </div>
	</nav>

<!-- **************************************************************************************************** -->
<!-- Jumbotron and Nav Bar right of page -->

	<div class="container-fluid">
      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">More Information</button>
          </p>
          <div class="jumbotron">
            <h1>Welcome To The University Of The West Indies St. Augustine</h1>
          </div>
        </div>


        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
          <div class="list-group">
            <a href="#" class="list-group-item active">Admissions</a>
            <a href="programmes.php" class="list-group-item">Our Programmes</a>
            <a href="#" class="list-group-item">Student Resources and Financial Aid</a>
            <a href="#" class="list-group-item">Map of UWI</a>
            <a href="#" class="list-group-item">Contact Us</a>
            <a href="#" class="list-group-item">Visit the Official Site</a>
          </div>
        </div>
      </div>

    </div>

<!-- **************************************************************************************************** -->
<!-- All other Sections -->

	<div id="section1" class="container-fluid">
	  <h1>About the UWI</h1>
	  <p>Oriens ex occidente lux – A Light Rising from the West</p>
	  <p>The University of the West Indies is a dynamic, international institution serving the countries of the Commonwealth Caribbean: Anguilla, Antigua/Barbuda, the Bahamas, Barbados, Belize, the British Virgin Islands, Cayman Islands, Dominica, Grenada, Jamaica, Montserrat, St. Christopher-Nevis, St. Lucia, St. Vincent and the Grenadines, Trinidad and Tobago and the Turks and Caicos Islands</p>
	  <p>At the UWI we aim to:</p>
	  <p><ul>
	  		<li>Advance Education</li>
	  		<li>Create Knowledge</li>
	  		<li>Support inclusive development of the Caribbean region and beyond</li>
	  </ul> </p>
	</div>
	<div id="section2" class="container-fluid">
	 <h1>Campus Life</h1>
	  <p>Our multicultural student body provide a unique campus experience.</p>
	  <p>Our student clubs offer an introduction to many cultures and encourage skill building as well foster healthy social interactions.</p>
	</div>
	<div id="section3" class="container-fluid">
	  <h1>Programmes</h1>
	  <p>Our 7 faculties, professional schools offer more than 200 programs to some 15,000 graduate, undergraduate and continuing studies students.</p>

	  <p>The UWI, St. Augustine ranks first in Trinidad and Tobago among accredited tertiary-level programmes.</p>
	</div>
	<div id="section4" class="container-fluid">
	  <h1>Admissions</h1>
	  <p>Want to save lives? Fight for justice? Explore your creativity through the arts? At the UWI St. Augustine, you can study biomedical technology,</p><p> law, dance, as well as hundreds of other programme options.</p>
	  <p>Apply to join our legion of UWI Pelicans and be part of the next generation of Caribbean leaders, thinkers and innovators.</p>
	  <p>Unsure of your options? Browse our programmes, take a campus tour, or speak with a student or staff liaison. We have personnel ready and willing to aid you on this exciting journey.</p>
	</div>

	<div id="section5" class="container-fluid">
	 <h1>Contact Us</h1>
		<p>Have more questions?</p>

		<p>Talk to the Student Advisory Services
		The Lloyd Braithwaite Building</p>

		<p>Email: student.advisory@sta.uwi.edu</p>
		<p>Tel: (868) 662-2002 ext 82096-8 / 82325 / 82360 / 82099</p>
		<p>Fax: (868) 663 0052</p>
		<p>Website: sta.uwi.edu/sas/</p>

		<p>Office Hours</p>
		<p>Monday to Friday</p>
		<p>8:30 a.m. - 4:30 p.m</p>
	</div>




	<script src="js/canvas.js"></script>
</body>



</html>
