<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Uwi Web App</title>

  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  	<link href="css/template2.css" rel="stylesheet">

	<style type="text/css">
	</style>
	
	<script>

</script>
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="50">
<!-- **************************************************************************************************** -->
<!-- Nav bar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">UWI MOBILE - Programmes</a>
      </div>
      <div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><a href="index.php">Home Page</a></li>
            <li><a href="#">How To Apply</a></li>
            <li><a href="#">Our Programmes</a></li>
            <li><a href="#">Contact Us</a></li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
<!-- **************************************************************************************************** -->
<!-- second Nav bar for search-->
<div class="tab">
    <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a href="#sectionA">Search All Programmes</a></li>
        <li><a href="#sectionB">Search by Subject</a></li>
      
    </ul>
    <div class="tab-content">

        <!-- Search All Programmes-->
        <div id="sectionA" class="tab-pane fade in active">

            <div id="col1" class="container">
              <h3>Choose a Faculty</h3>
              <ul class="nav nav-pills nav-stacked">
                <li class="active"><a href="#prog" data-toggle="pill" onclick="retrieveProgrammes(1)">Faculty of Engineering</a></li>
                <li><a href="#prog" data-toggle="pill" onclick="retrieveProgrammes(2)">Faculty of Food & Agriculture</a></li>
                <li><a href="#prog" data-toggle="pill" onclick="retrieveProgrammes(3)">Faculty of Humanities & Education</a></li>
                <li><a href="#prog" data-toggle="pill" onclick="retrieveProgrammes(4)">Faculty of Law</a></li>
                <li><a href="#prog" data-toggle="pill" onclick="retrieveProgrammes(5)">Faculty of Medical Sciences</a></li>
                <li><a href="#prog" data-toggle="pill" onclick="retrieveProgrammes(6)">Faculty of Science & Technology</a></li>
                <li><a href="#prog" data-toggle="pill" onclick="retrieveProgrammes(7)">Faculty of Social Sciences</a></li>
              </ul>
            </div>

            <div id="col2" class="container">
              <div class="tab-content">
                <div id="prog" class="tab-pane fade in active">
                    <h3>Choose a Undergraduate Degree</h3>
                      <ul id="tab1" class="nav nav-pills nav-stacked">
                      </ul>
                </div>
              </div>
            </div>

            <div id="col2" class="container">
              <div class="tab-content">
                <div id="prog1" class="tab-pane fade in active">
                    <h3>Choose a Programme</h3>
                      <ul id="tab2" class="nav nav-pills nav-stacked">
                      </ul>
                </div>
              </div>
            </div>
            
            <div id="hh">
              <p></p>
            </div>
        </div>

        <!-- Search by Grades -->
        <div id="sectionB" class="tab-pane fade">
            <h3>Choose Your Lower Education Passes</h3>
            <ul class="lower_edu_sec nav nav-pills nav-stacked">
              
            </ul>

            <div id="lower_edu_choose_sub" class="container collapse">
                
              <form style="display:none" id="input_chosen_lvl1">

              </form>

              <div id="display_chosen_lvl1">
                <div class="form-group">

                </div>
              </div>
              <div id="lvl1_add_sub">
                <input id="subToEnter" type="text" class="form-control" placeholder="Subject">
                <button onclick="addSublvl1();" type="button" class="btn btn-primary">Add Subject</button>
              </div>
              
            </div>
            <!-- seperator -->
            <h3>Choose Your Higher Education Passes</h3>
            <ul id="insertHere" class="higher_edu_sec nav nav-pills nav-stacked">
              
            </ul>

            <div id="higher_edu_choose_sub" class="container collapse">
                
              <form style="display:none" id="input_chosen_lvl2">

              </form>

              <div id="display_chosen_lvl2">
                <div class="form-group">

                </div>
              </div>
              <div id="lvl2_add_sub">
                <input id="subToEnter2" type="text" class="form-control" placeholder="Subject">
                <button onclick="addSublvl2();" type="button" class="btn btn-primary">Add Subject</button>
              </div>

              <!-- appears only when submit button is hit -->
              <div class="tab-content">
                <div class="tab-pane fade in active">
                    <h3>Choose a Programme</h3>
                      <ul id="programmes_inserted" class="nav nav-pills nav-stacked">
                      </ul>
                </div>
              </div>
              
            </div>

            <div class="modal-footer">
                <input onclick="submit();" type="button" value="SUBMIT" class="btn"/>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="modal_notif_invalid" role="dialog">
              <div class="modal-dialog">
              
                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Incorrect Data Entered</h4>
                  </div>
                  <div class="modal-body">
                    <p>The data entered should only contain alphabetical charaters and must not have a length of 0</p> 
                    <p>Please Try Again</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
                
              </div>
            </div>
        </div>

       
    </div>
</div>


<!-- **************************************************************************************************** -->
<!-- Modal Window -->

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">

    
      <div id="mod" class="modal-content">

      <!-- programme name -->
        <div id="name" class="modal-header">
          
        </div>


        <div id="desc" class="modal-body">
        
        </div>

        <hr>

        <div id="time" class="modal-body">
        
        </div>
        
        <hr>

        <div id="edu1" class="modal-body">
        
        </div>

        <hr>

        <div id="edu2" class="modal-body">
        
        </div>

        <hr>

        <div id="edu3" class="modal-body">
        
        </div>

         <hr>
        
        <div id="career" class="modal-body">
        
        </div>

         <hr>
        
        <div id="job" class="modal-body">
        
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>


      </div>




    </div>
  </div>

<!-- **************************************************************************************************** -->

<!-- <script id="scroll" type="text/javascript">
  $("#prog li a[href^='#']").on('click', function(e) {

       // prevent default anchor click behavior
       e.preventDefault();
       
       // animate
       $('html, body').animate({
           scrollTop: $(this.hash).offset().top-75
         }, 300, function(){
   
           // when done, add hash to url
           // (default click behaviour)
           window.location.hash = this.hash;
         });

    });
</script> -->

<script src="js/programmes.js"></script>
<script src="js/programmes2.js"></script>
</body>


</html>